const taskListTypes = {
  // CREATE
  // READ
  READ_ALL_STATE: 'READ_ALL_STATE',
  // UPDATE
  UPDATE_ALL_STATE: 'UPDATE_ALL_STATE',
  UPDATE_TASK_FINISH_STATUS: 'UPDATE_TASK_FINISH_STATUS',
  // DELETE
  DELETE_ALL_STATE: 'DELETE_ALL_STATE',
  DELETE_TASK_FINISH_STATUS: 'DELETE_TASK_FINISH_STATUS',
};

export default taskListTypes;
