const taskListTypes = {
  // CREATE
  CREATE_NEW_TASK: 'CREATE_NEW_TASK',
  // READ
  READ_ALL_STATE: 'READ_ALL_STATE',
  // UPDATE
  UPDATE_TASK_LIST_ITEM: 'UPDATE_TASK_LIST_ITEM',
  // DELETE
  DELETE_ALL_STATE: 'DELETE_ALL_STATE',
  DELETE_TASK: 'DELETE_TASK',
};

export default taskListTypes;
